"""add sales table

Revision ID: 0317b29a66aa
Revises: f47c479f5342
Create Date: 2026-05-31 23:23:31.177933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0317b29a66aa'
down_revision: Union[str, Sequence[str], None] = 'f47c479f5342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
