"""rebuild query_history

Revision ID: 402404cdc559
Revises: 0317b29a66aa
Create Date: 2026-06-01 20:31:40.047504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402404cdc559'
down_revision: Union[str, Sequence[str], None] = '0317b29a66aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_history', sa.Column('sql', sa.Text(), nullable=False))
    op.add_column('query_history', sa.Column('row_count', sa.Integer(), nullable=False))
    op.alter_column('query_history', 'execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('query_history_user_id_fkey'), 'query_history', type_='foreignkey')
    op.drop_column('query_history', 'user_id')
    op.drop_column('query_history', 'generated_sql')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_history', sa.Column('generated_sql', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('query_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('query_history_user_id_fkey'), 'query_history', 'users', ['user_id'], ['id'])
    op.alter_column('query_history', 'execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('query_history', 'row_count')
    op.drop_column('query_history', 'sql')
    # ### end Alembic commands ###
