"""add user_email to query history

Revision ID: 61b0829b0492
Revises: 927f887273d5
Create Date: 2026-06-03 21:32:44.764661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b0829b0492'
down_revision: Union[str, Sequence[str], None] = '927f887273d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_history', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_history', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
