"""add user_email to query history

Revision ID: 927f887273d5
Revises: 402404cdc559
Create Date: 2026-06-03 00:38:30.354385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927f887273d5'
down_revision: Union[str, Sequence[str], None] = '402404cdc559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_history', sa.Column('user_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_history', 'user_email')
    # ### end Alembic commands ###
