"""make user_email nullable

Revision ID: acdbdd9136bd
Revises: 61b0829b0492
Create Date: 2026-06-03 22:23:10.935902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acdbdd9136bd'
down_revision: Union[str, Sequence[str], None] = '61b0829b0492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_history', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_history', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
